import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

import { describe, expect, test } from 'vitest'

import {
  DEMUCS_SPEC_PAD,
  STFT_FREQ_BINS,
  STFT_HOP,
  STFT_N_FFT,
  buildCacInput,
  centeredNormalizedIstft,
  centeredNormalizedStft,
  combineFrequencyAndTimeBranches,
  decodeCacOutputToWaveforms,
  demucsForwardSpec,
  demucsInverseSpec,
} from '../../../src/infrastructure/onnx-worker/stft'
import { MODEL_SEGMENT_SAMPLES } from '../../../src/infrastructure/onnx-worker/windowing'

/**
 * Independent golden vector for the raw centered/normalized STFT: numpy-
 * generated bins for a fixed seeded signal, using the exact method S2
 * validated against torch.stft (spikes/s2/generate_stft_fixture.py,
 * reproduced read-only in this task since spike/s2-onnx-runtime does not
 * carry its own fixture output file). The fixture signal is trimmed to 4096
 * samples; a Python check confirmed this trim reproduces frame0/frame1
 * bit-for-bit against the full 44100-sample signal, because STFT frames only
 * depend on samples up to their own window.
 */
interface StftFixture {
  readonly n_fft: number
  readonly hop: number
  readonly signal: readonly number[]
  readonly frame0_re: readonly number[]
  readonly frame0_im: readonly number[]
  readonly frame1_re: readonly number[]
  readonly frame1_im: readonly number[]
}

/**
 * Independent golden vector for HTDemucs' own `_spec`/`_ispec` (not the raw
 * STFT): generated by porting spikes/s2/compare_onnx.py's `demucs_spec`/
 * `demucs_ispec` line-for-line into Python/numpy and running it read-only
 * against the venv at D:\cursos\separador-pistas\.venv. Note this pair is
 * NOT a lossless round trip by design (it drops the Nyquist bin and trims to
 * the middle `ceil(N/hop)` frames, matching HTDemucs' own lossy spectral
 * encoding that the model's learned mask compensates for) -- confirmed by
 * running the S2 reference against itself at the real segment length
 * (343980 samples), which reproduces an original signal with ~0.35 max abs
 * error, not ~1e-6. So `ispec_identity_reconstructed` is the fixture's
 * golden *value*, not an expectation that it equals the original signal.
 */
interface DemucsSpecFixture {
  readonly n_fft: number
  readonly hop: number
  readonly length: number
  readonly signal: readonly number[]
  readonly spec_real: readonly (readonly number[])[] // [bin][frame]
  readonly spec_imag: readonly (readonly number[])[]
  readonly frame_count: number
  readonly ispec_identity_reconstructed: readonly number[]
}

function loadFixture<T>(name: string): T {
  const fixturePath = path.join(path.dirname(fileURLToPath(import.meta.url)), 'fixtures', name)
  return JSON.parse(readFileSync(fixturePath, 'utf-8')) as T
}

function fixtureSignal(length: number, phase = 0): Float64Array {
  return Float64Array.from({ length }, (_, index) => Math.sin((index + phase) * 0.0091) + 0.3 * Math.cos(index * 0.021))
}

function maxAbsDiff(a: ArrayLike<number>, b: ArrayLike<number>): number {
  let maximum = 0
  for (let index = 0; index < a.length; index += 1) {
    maximum = Math.max(maximum, Math.abs(a[index] - b[index]))
  }
  return maximum
}

describe('STFT/iSTFT constants', () => {
  test('match the S2 Basic spectral parameters', () => {
    expect(STFT_N_FFT).toBe(4096)
    expect(STFT_HOP).toBe(1024)
    expect(STFT_FREQ_BINS).toBe(2048)
    expect(DEMUCS_SPEC_PAD).toBe(1536)
  })
})

describe('centeredNormalizedStft / centeredNormalizedIstft', () => {
  test('round-trips a deterministic signal within 1e-6', () => {
    const signal = fixtureSignal(9000)
    const frames = centeredNormalizedStft(signal)
    const reconstructed = centeredNormalizedIstft(frames, signal.length)

    expect(maxAbsDiff(reconstructed, signal)).toBeLessThanOrEqual(1e-6)
  })

  test('matches the independent numpy golden bins for frame 0 and frame 1', () => {
    const fixture = loadFixture<StftFixture>('stft-golden.json')
    const signal = Float64Array.from(fixture.signal)

    const frames = centeredNormalizedStft(signal)

    expect(maxAbsDiff(frames[0].real, fixture.frame0_re)).toBeLessThanOrEqual(1e-6)
    expect(maxAbsDiff(frames[0].imaginary, fixture.frame0_im)).toBeLessThanOrEqual(1e-6)
    expect(maxAbsDiff(frames[1].real, fixture.frame1_re)).toBeLessThanOrEqual(1e-6)
    expect(maxAbsDiff(frames[1].imaginary, fixture.frame1_im)).toBeLessThanOrEqual(1e-6)
  })

  test('rejects reflect padding at least as large as the signal', () => {
    const tooShort = fixtureSignal(2048)
    expect(() => centeredNormalizedStft(tooShort)).toThrow('stft.invalid_pad')
  })

  test('rejects an inverse frame with the wrong bin count', () => {
    expect(() =>
      centeredNormalizedIstft([{ real: new Float64Array(3), imaginary: new Float64Array(3) }], 4096),
    ).toThrow('stft.invalid_bins')
  })
})

describe('demucsForwardSpec / demucsInverseSpec', () => {
  test('drops the Nyquist bin and produces ceil(N/hop) frames', () => {
    const signal = fixtureSignal(MODEL_SEGMENT_SAMPLES)
    const spectrum = demucsForwardSpec(signal)

    const expectedFrames = Math.ceil(MODEL_SEGMENT_SAMPLES / STFT_HOP)
    expect(expectedFrames).toBe(336)
    expect(spectrum.frameCount).toBe(expectedFrames)
    expect(spectrum.frames).toHaveLength(expectedFrames)
    for (const frame of spectrum.frames) {
      expect(frame.real).toHaveLength(STFT_FREQ_BINS)
      expect(frame.imaginary).toHaveLength(STFT_FREQ_BINS)
    }
  })

  test('matches the independent Python demucs_spec/demucs_ispec reference bins and identity-mask reconstruction', () => {
    const fixture = loadFixture<DemucsSpecFixture>('demucs-spec-golden.json')
    const signal = Float64Array.from(fixture.signal)

    const spectrum = demucsForwardSpec(signal)
    expect(spectrum.frameCount).toBe(fixture.frame_count)

    for (let frame = 0; frame < fixture.frame_count; frame += 1) {
      const expectedReal = fixture.spec_real.map((bin) => bin[frame])
      const expectedImaginary = fixture.spec_imag.map((bin) => bin[frame])
      expect(maxAbsDiff(spectrum.frames[frame].real, expectedReal)).toBeLessThanOrEqual(1e-6)
      expect(maxAbsDiff(spectrum.frames[frame].imaginary, expectedImaginary)).toBeLessThanOrEqual(1e-6)
    }

    // Applying an identity mask (feeding the forward spec straight back into
    // the inverse, as if the model's freq output equalled its mag input) is
    // the exact operation `demucsIspec` performs on real model output; this
    // proves our port matches Python's number, not that it recovers `signal`.
    const identityReconstructed = demucsInverseSpec(spectrum.frames, fixture.length)
    expect(maxAbsDiff(identityReconstructed, fixture.ispec_identity_reconstructed)).toBeLessThanOrEqual(1e-6)
  })

  test('rejects an inverse spectrum frame with the wrong bin count', () => {
    expect(() =>
      demucsInverseSpec([{ real: new Float64Array(10), imaginary: new Float64Array(10) }], 4096),
    ).toThrow('stft.invalid_bins')
  })
})

describe('CAC layout', () => {
  test('lays out [L.real, L.imag, R.real, R.imag] as flat row-major [4, freqBins, frames]', () => {
    const length = 5000
    const left = fixtureSignal(length, 1)
    const right = fixtureSignal(length, 2)

    const cac = buildCacInput(left, right)
    const leftSpec = demucsForwardSpec(left)
    const rightSpec = demucsForwardSpec(right)
    const frameCount = cac.frameCount

    expect(frameCount).toBe(leftSpec.frameCount)
    expect(cac.data).toHaveLength(4 * STFT_FREQ_BINS * frameCount)

    const sampleBin = 17
    const sampleFrame = 3
    const at = (channel: number) => channel * STFT_FREQ_BINS * frameCount + sampleBin * frameCount + sampleFrame

    expect(cac.data[at(0)]).toBeCloseTo(leftSpec.frames[sampleFrame].real[sampleBin], 5)
    expect(cac.data[at(1)]).toBeCloseTo(leftSpec.frames[sampleFrame].imaginary[sampleBin], 5)
    expect(cac.data[at(2)]).toBeCloseTo(rightSpec.frames[sampleFrame].real[sampleBin], 5)
    expect(cac.data[at(3)]).toBeCloseTo(rightSpec.frames[sampleFrame].imaginary[sampleBin], 5)
  })

  test('rejects channels that produce mismatched frame counts', () => {
    const left = fixtureSignal(5000) // ceil(5000 / 1024) = 5 frames
    const right = fixtureSignal(3000) // ceil(3000 / 1024) = 3 frames
    expect(() => buildCacInput(left, right)).toThrow('stft.channel_mismatch')
  })

  test('encoding to CAC and decoding back reproduces the same complex bins used to build it', () => {
    const length = 5000
    const left = fixtureSignal(length, 1)
    const right = fixtureSignal(length, 2)

    const cac = buildCacInput(left, right)
    const directLeft = demucsInverseSpec(demucsForwardSpec(left).frames, length)
    const directRight = demucsInverseSpec(demucsForwardSpec(right).frames, length)

    // Single-source identity mask: the "model" returns exactly the mag it
    // was given, so decoding must reproduce the same iSTFT as calling
    // demucsInverseSpec directly on the pre-CAC frames (up to Float32
    // packing precision in the CAC buffer).
    const [decodedLeft, decodedRight] = decodeCacOutputToWaveforms(cac.data, 1, cac.frameCount, length)[0]

    expect(maxAbsDiff(decodedLeft, directLeft)).toBeLessThanOrEqual(1e-6)
    expect(maxAbsDiff(decodedRight, directRight)).toBeLessThanOrEqual(1e-6)
  })
})

describe('branch reconstruction', () => {
  test('combines equal-length frequency and time branches elementwise', () => {
    const frequency = Float64Array.from([1, 2, 3])
    const time = Float64Array.from([0.5, -1, 2])

    const combined = combineFrequencyAndTimeBranches(frequency, time)

    expect(Array.from(combined)).toEqual([1.5, 1, 5])
  })

  test('rejects mismatched branch lengths', () => {
    expect(() => combineFrequencyAndTimeBranches(new Float64Array(3), new Float64Array(4))).toThrow(
      'stft.branch_length_mismatch',
    )
  })

  test('sums the golden frequency-branch reconstruction with a synthetic time branch', () => {
    const fixture = loadFixture<DemucsSpecFixture>('demucs-spec-golden.json')
    const frequencyBranch = Float64Array.from(fixture.ispec_identity_reconstructed)
    const timeBranch = fixtureSignal(fixture.length, 21)

    const combined = combineFrequencyAndTimeBranches(frequencyBranch, timeBranch)
    const expected = Float64Array.from({ length: fixture.length }, (_, index) => frequencyBranch[index] + timeBranch[index])

    expect(maxAbsDiff(combined, expected)).toBe(0)

    const zeroTimeBranch = new Float64Array(fixture.length)
    expect(maxAbsDiff(combineFrequencyAndTimeBranches(frequencyBranch, zeroTimeBranch), frequencyBranch)).toBe(0)
  })
})
